code --install-extension 13xforever.language-x86-64-assembly
code --install-extension apollographql.vscode-apollo
code --install-extension arcanis.vscode-zipfs
code --install-extension artdiniz.quitcontrol-vscode
code --install-extension bcanzanella.openmatchingfiles
code --install-extension be5invis.vscode-custom-css
code --install-extension blakeh.jump-to-test
code --install-extension bradlc.vscode-tailwindcss
code --install-extension cesium.gltf-vscode
code --install-extension clinyong.vscode-css-modules
code --install-extension dbaeumer.vscode-eslint
code --install-extension docker.docker
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension geddski.macros
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension graphql.vscode-graphql
code --install-extension graphql.vscode-graphql-syntax
code --install-extension hashicorp.terraform
code --install-extension heybourn.headwind
code --install-extension jebbs.plantuml
code --install-extension mechatroner.rainbow-csv
code --install-extension midnightsyntax.vscode-wrap-console-log
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.vscode-speech
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension perkovec.emoji
code --install-extension redhat.java
code --install-extension rust-lang.rust-analyzer
code --install-extension simonsiefke.svg-preview
code --install-extension snyk-security.snyk-vulnerability-scanner
code --install-extension svelte.svelte-vscode
code --install-extension unclebeast.har-viewer
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension yoavbls.pretty-ts-errors
