code --install-extension 13xforever.language-x86-64-assembly
code --install-extension apollographql.vscode-apollo
code --install-extension arcanis.vscode-zipfs
code --install-extension artdiniz.quitcontrol-vscode
code --install-extension bcanzanella.openmatchingfiles
code --install-extension blakeh.jump-to-test
code --install-extension bradlc.vscode-tailwindcss
code --install-extension cesium.gltf-vscode
code --install-extension clinyong.vscode-css-modules
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension geddski.macros
code --install-extension github.vscode-github-actions
code --install-extension GraphQL.vscode-graphql
code --install-extension GraphQL.vscode-graphql-syntax
code --install-extension hashicorp.terraform
code --install-extension heybourn.headwind
code --install-extension midnightsyntax.vscode-wrap-console-log
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension Perkovec.emoji
code --install-extension rust-lang.rust-analyzer
code --install-extension SimonSiefke.svg-preview
code --install-extension svelte.svelte-vscode
code --install-extension vscode-icons-team.vscode-icons
